// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Query struct {
}

type User struct {
	ID                       string         `json:"id"`
	Email                    *string        `json:"email,omitempty"`
	EmailVerified            bool           `json:"email_verified"`
	SignupMethods            string         `json:"signup_methods"`
	GivenName                *string        `json:"given_name,omitempty"`
	FamilyName               *string        `json:"family_name,omitempty"`
	MiddleName               *string        `json:"middle_name,omitempty"`
	Nickname                 *string        `json:"nickname,omitempty"`
	PreferredUsername        *string        `json:"preferred_username,omitempty"`
	Gender                   *string        `json:"gender,omitempty"`
	Birthdate                *string        `json:"birthdate,omitempty"`
	PhoneNumber              *string        `json:"phone_number,omitempty"`
	PhoneNumberVerified      *bool          `json:"phone_number_verified,omitempty"`
	Picture                  *string        `json:"picture,omitempty"`
	Roles                    []string       `json:"roles"`
	CreatedAt                *int64         `json:"created_at,omitempty"`
	UpdatedAt                *int64         `json:"updated_at,omitempty"`
	RevokedTimestamp         *int64         `json:"revoked_timestamp,omitempty"`
	IsMultiFactorAuthEnabled *bool          `json:"is_multi_factor_auth_enabled,omitempty"`
	AppData                  map[string]any `json:"app_data,omitempty"`
}

type VerificationRequest struct {
	ID          string  `json:"id"`
	Identifier  *string `json:"identifier,omitempty"`
	Token       *string `json:"token,omitempty"`
	Email       *string `json:"email,omitempty"`
	Expires     *int64  `json:"expires,omitempty"`
	CreatedAt   *int64  `json:"created_at,omitempty"`
	UpdatedAt   *int64  `json:"updated_at,omitempty"`
	Nonce       *string `json:"nonce,omitempty"`
	RedirectURI *string `json:"redirect_uri,omitempty"`
}
