gqlgen-generate:
	go get github.com/99designs/gqlgen/codegen/config@v0.17.75
	go get github.com/99designs/gqlgen/internal/imports@v0.17.75
	go get github.com/99designs/gqlgen/api@v0.17.75
	go get github.com/99designs/gqlgen@v0.17.75
	go run github.com/99designs/gqlgen generate